version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: my-rabbit
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmqdata:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - rabbitmqlogs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

  orderApi:
    build: ./OrderApi
    image: order.api
    container_name: order.api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_HOSTNAME=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  emailWorker:
    build: ./EmailWorker
    image: email-worker
    container_name: email-worker
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBIT_HOSTNAME=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    restart: on-failure

  auditQueue:
    build: ./AuditQueue
    image: audit-queue
    container_name: audit-queue
    ports:
      - 5101:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RABBIT_HOSTNAME=rabbitmq
      - MONGO_HOSTNAME=mongodb
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongodata:
  rabbitmqdata:
  rabbitmqlogs:
